/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ImageUploader: typeof import('./components/form/ImageUploader.vue')['default']
    PhoneInput: typeof import('./components/PhoneInput.vue')['default']
    PhoneInputField: typeof import('./components/PhoneInputField.vue')['default']
    PhoneInputFieled: typeof import('./components/PhoneInputFieled.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toast: typeof import('./components/Toast.vue')['default']
    UploadImageField: typeof import('./components/form/UploadImageField.vue')['default']
    UploadImageInputField: typeof import('./components/form/UploadImageInputField.vue')['default']
  }
}
